backend:
  name: github
  repo: newsch/newsch.github.io
  branch: netlifycms
media_folder: "assets/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/thoughts"
    create: true
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Categories", name: "categories", widget: "list", required: false}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Draft", name: "draft", widget: "boolean", default: true}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "projects"
    label: "Projects"
    folder: "content/things"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Start Date", name: "date", widget: "date"}
      - {label: "End Date", name: "enddate", widget: "date", required: false}
      - {label: "Categories", name: "categories", widget: "list", required: false}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Draft", name: "draft", widget: "boolean", default: true}
      - {label: "Body", name: "body", widget: "markdown"}
